### ISSUE TITLE
Add a section of Tags

### ISSUE THREAD

**Issue by MRIDUL-MB** [MRIDUL-MB/dsa_web#15]
![image](https://user-images.githubusercontent.com/53037689/197450054-5d847412-cf82-4569-b359-58f77065b226.png)

Create a section of tags so that we can put the tag over the question, we have the tags(in the form of a list) in the database.
Path of file :- [src](https://github.com/MRIDUL-MB/dsa_web/tree/master/src)/[components](https://github.com/MRIDUL-MB/dsa_web/tree/master/src/components)/QAcards.js

**Comment by rupak2001** [comment]
Hi, i would like to contribute on this issue

**Comment by MRIDUL-MB** [comment]
Sure, Please go ahead.
If you face any problems, feel free to discuss them here!
