### ISSUE TITLE
Fix the mobile UI

### ISSUE THREAD

**Issue by MRIDUL-MB** [MRIDUL-MB/dsa_web#18]
This is desktop preview:-
![image](https://user-images.githubusercontent.com/53037689/197468939-ae5ca06d-90ef-4d1f-be0e-a1663ec0ab63.png)
-----------------------------------------------------------------------------------------------------
This is Mobile preview:-
![image](https://user-images.githubusercontent.com/53037689/197469039-7e82651b-3547-44f0-ae71-9b012263575b.png)

Fix the CSS for the mobile screen.

**Comment by avezqureshi14** [comment]
Can you assign this to me

**Comment by MRIDUL-MB** [comment]
Sure, please go ahead!

**Comment by MRIDUL-MB** [comment]
Are you working on it?
